### ISSUE TITLE
I have issued with the CMM dataset

### ISSUE THREAD

**Issue by khan008** [CORSMAL/safe_handover#3]
Traceback (most recent call last):
  File "evaluate_handover.py", line 544, in <module>
    container_trajectory = loadContainerTrajectory(new_CCM_fname, dataset)
  File "evaluate_handover.py", line 236, in loadContainerTrajectory
    measured_traj.append([pos[0], pos[1], pos[2] + TRAJECTORY_Z_OFFSET])
IndexError: list index out of range

Also throwing this error then i just create a dummy txt file, afterwards the above error was throwing. Please help with me it, Thanks
data/CCM/vision_estimations/train/volume_estimation/000618_properties.txt

**Comment by yiklungpang** [comment]
Please make sure you have ran the perception pipeline before starting the handover simulation. The perception pipeline outputs the estimated object trajectory (in the txt file) which will be used in the simulation.

Also see commit 580abebeca05385fc091d99b69b8de80d887dfc3 if you are having issues with the CCM dataset format.
